---
title: 'Aftermath of Apple Picking - So Many Apples'
summary: 
authors:
  - admin
date: '2019-10-20'
image:
  caption: '[Photo by Thomas Millot on Unsplash](https://unsplash.com/photos/bInuR-nuU9o)'
focal_point: 'center'
categories: [life]
tags: [apple]
---


I recently went to apple picking on a sunny weekend. Fall in Michigan especially around this time is very beautiful. Going to apple picking is a nice activity to enjoy the fall foliage in the country and get some workout by working and picking the apples.

The [apple pick farm](https://www.wasemfruitfarm.com/) I went was pretty nice. I loved their warm donuts, despite there was a wait. The minimum apples to purchase was to fill a half [bushel](https://en.wikipedia.org/wiki/Bushel)! It is A LOT apples!

Here are some things I did/plan to do:

- Eat an apple a day for a week during lunch
- Bring a bag to work to share with coworkers
- Give a bag to the neighbor
- Cook them!

some cooking recopies:

- [Pork Chop with Apple and Onion](https://www.laurainthekitchen.com/recipes/skillet-pork-chops-with-apples-and-onions/) 

I used 4 Pork Chop (the kind that doesn't have bones) and 2 big apples

- [Apple Butter](https://www.allrecipes.com/recipe/268029/chef-johns-apple-butter/)

I liked this idea and recipe. I have never had apple butter, but it does tastes very good. Since I eat a toast for breakfast basically everyday, so I can definitely see the use of this butter!

Ingredients: 

+ 5 pounds of apples (around 12 apples, I used a mix of all the apples I have) </br>
+ 3/4 cup of white sugar and half cup of brown sugar </br>
+ one tsp cinnamon, one tsp salt, half tsp nutmeg, half tsp allspice </br>
+ 1/4 cup of apple vinegar





